Update database
DanWilkins2107/TheatreApp pull request #32
Opened 2024-04-06 19:51 UTC by DanWilkins2107

2024-04-15 12:32 UTC, dwulfse commented
is this meant to be a PR? its just all the availability stuff again

2024-04-15 15:24 UTC, DanWilkins2107 commented
Yeah reset still doesn't work. Idk why plz let me know if u can figure out why, all changes from availability have been made on this PR

2024-06-06 18:18 UTC, dwulfse requested changes

2024-06-06 18:18 UTC, dwulfse commented on components/Availability/AvailabilityCalendar.jsx
> +        scrollViewRef.current.scrollTo({ y:635, animated: true });
this is currently scrolling back up to 8:00 every time I change availability

2024-06-06 18:18 UTC, dwulfse commented on components/Availability/AvailabilityCalendar.jsx
> +        scrollViewRef.current.scrollTo({ y:635, animated: true });
also doesn't scroll to 8:00 when opening the availability screen

2024-06-06 18:18 UTC, dwulfse commented on components/Availability/AvailabilityCalendar.jsx
> +                <DateTimePicker
bit of a weird one but this is formatted as "6 Jun 2024" 99% of the time then goes to "30/06/2024" for some dates, very randomly

2024-06-06 18:18 UTC, dwulfse commented on screens/ProductionScreens/Availability.jsx
> +                <SmallFormButton title="Reset" backgroundColor="bg-white" onPress={onReset} />
can't work out why reset isn't working yet. works the first time then never again

2024-07-04 09:29 UTC, dwulfse commented
this is so cool omg

2024-07-05 10:04 UTC, dwulfse requested changes

2024-07-05 10:04 UTC, dwulfse commented on components/Availability/AvailabilityCalendar.jsx
> +                <View className="flex-row flex-1 border-t border-r bg-slate-100">
try no border

2024-07-05 10:04 UTC, dwulfse commented on components/Availability/AvailabilityCalendar.jsx
> +                {/* Any Thoughts on whether we want this line when the week is not current? */}
quite undecided, reckon leave it everywhere for now just cos its cool, then can think about it later

2024-07-05 10:04 UTC, dwulfse commented on screens/ProductionScreens/Availability.jsx
> +    const onSubmit = async () => {
disable buttons on submit/ reset

2024-07-05 10:04 UTC, dwulfse commented on components/Availability/AvailabilityCalendar.jsx
> +import { set } from "firebase/database";
set not used

2024-07-09 10:12 UTC, dwulfse requested changes
just performance to worry about

2024-07-09 10:12 UTC, dwulfse commented on components/Availability/AvailabilityCalendar.jsx
> +                <View className="flex-row flex-1  bg-slate-100">
ugly background

2024-07-09 11:30 UTC, dwulfse approved these changes

2024-07-09 11:30 UTC, merged