Budget Main Screen
DanWilkins2107/TheatreApp pull request #45
Opened 2024-07-09 19:29 UTC by DanWilkins2107

2024-07-11 10:06 UTC, dwulfse requested changes

2024-07-11 10:06 UTC, dwulfse commented on components/Budget/ImageViewer.jsx
help me understand what RecieptViewer and ImageViewer are

2024-07-11 10:06 UTC, dwulfse commented on components/Budget/ExpenseSummary.jsx
> +                    <View className="flex-row items-center">
check overflow

2024-07-11 10:06 UTC, dwulfse commented on components/Budget/ExpenseSummary.jsx
> +                            <Icon
try line up the edit icons

2024-07-11 10:06 UTC, dwulfse commented on screens/ProductionScreens/BudgetMain.jsx
> +    const filterExpenses = (expenses) => {
check time ordering

2024-07-11 10:06 UTC, dwulfse commented on screens/ProductionScreens/BudgetMain.jsx
> +                    </ScrollView>
lil spacer at the bottom

2024-07-11 10:06 UTC, dwulfse commented on screens/ProductionScreens/BudgetMain.jsx
> +                        <Title extraClassName="mb-4 text-center">Expenses</Title>
if you can find some more space at the top that would be beautiful

2024-07-11 10:11 UTC, DanWilkins2107 commented on components/Budget/ImageViewer.jsx
RecieptViewer is the component for adding a receipt to an expense. RecieptViewerModal is the modal that pops up whenever we click on an image. ImageViewer is the picture in the dropdown when viewing an expense.

2024-07-11 10:47 UTC, DanWilkins2107 commented on screens/ProductionScreens/BudgetMain.jsx
> +                        <Title extraClassName="mb-4 text-center">Expenses</Title>
Honestly I don't have a clue what I could remove lol
Feel like if I get rid of any margin/padding it'll just look too cramped

2024-07-11 11:38 UTC, dwulfse commented on screens/ProductionScreens/BudgetMain.jsx
> +                                        <Subtitle extraClassName="ml-4">
check box on text press

2024-07-11 11:40 UTC, dwulfse commented on components/Budget/ExpenseSummary.jsx
> +                                    </Text>
remove colon

2024-07-11 12:06 UTC, dwulfse commented on components/Budget/ExpenseSummary.jsx
> +                        <ProfilePicture
can this get a grey outline for placeholder

2024-07-11 12:07 UTC, dwulfse commented on components/Budget/ExpenseSummary.jsx
> +                        <ProfilePicture
think being able to change outline colour is a good shout generally, could do some things with diff outlines for admins n that

2024-07-11 12:09 UTC, dwulfse commented on components/Budget/ExpenseSummary.jsx
> +                                        <ImageViewer URL={expense.receipt} centered />
think the spacing around the reciept looks slightly odd- too much at the side/ not enough at the bottom

2024-07-11 12:13 UTC, dwulfse commented on components/Budget/BudgetLineGraph.jsx
> +            [0, 33, 75, 100],
play with where the green ends

2024-07-12 12:10 UTC, dwulfse commented on components/Budget/ExpenseSummary.jsx
> +                                        Receipt
remove "receipt" completely

2024-07-12 12:13 UTC, dwulfse approved these changes

2024-07-12 12:13 UTC, merged